helmDefaults:
  createNamespace: false
  timeout: 480
  atomic: true
  wait: true
  
environments:
  stage:

releases:
- name: ax-db
  chart: ./service-chart
  namespace: test
  values:
    - ./service-chart/stage-service.yaml
  secrets:
    - ./service-chart/stage.secrets.yaml
  set:
    - name: image.repository
      value: {{ requiredEnv "ECR_REPOSITORY_BASE_URL" }}/athletex-db
    - name: image.tag
      value: {{ requiredEnv "IMAGE_TAG" }}      
